CREATE TABLE [dbo].[CLIENTRELATION]
(
	[IDClientRelation] INT NOT NULL PRIMARY KEY IDENTITY,
	[IdClientParent] [int] NULL,
	[IdClientRelative] [int] NULL,
	CONSTRAINT [FK_CLIENTRELATION_CLIENTPARENT] FOREIGN KEY([IdClientParent]) REFERENCES [dbo].[CLIENT] ([IDClient]),
	CONSTRAINT [FK_CLIENTRELATION_CLIENTRELATIVE] FOREIGN KEY([IdClientRelative]) REFERENCES [dbo].[CLIENT] ([IDClient]),
)
