CREATE TABLE [dbo].[COMPANY]
(
	[IDComp] INT NOT NULL PRIMARY KEY IDENTITY,
	[AcronymComp] [nvarchar](10) NULL,
	[TitleComp] [nvarchar](150) NULL,
	[PhoneOffice] [nvarchar](20) NULL,
	[PhoneOwner] [nvarchar](20) NULL,
	[StreetComp] [nvarchar](100) NULL,
	[CountyComp] [nvarchar](50) NULL,
	[ZipcodeComp] [nvarchar](10) NULL,
	[PartPayeBraid] [real] NULL,
	[IDOwnerBraider] [int] NULL,
	[CostHairDeduct] [money] NULL,
	[PriceTakeOff] [money] NULL,
	[IdMainRegister] [int] NULL,
	[StateTaxOnSale] [real] NULL,
	[StateTaxOnBraiding] [real] NULL,
	[StateCompany] [nchar](2) NULL,
	[EmailComp] [nvarchar](100) NULL,
	[WebsiteComp] [nvarchar](100) NULL,
	[CreationDate] [date] NULL,
	[AppointWithStyleTime] [bit] NULL,
	[Monday] [bit] NULL,
	[MondayTime] [time](7) NULL,
	[Tuesday] [bit] NULL,
	[TuesdayTime] [time](7) NULL,
	[Wednesday] [bit] NULL,
	[WednesdayTime] [time](7) NULL,
	[Thursday] [bit] NULL,
	[ThursdayTime] [time](7) NULL,
	[Friday] [bit] NULL,
	[FridayTime] [time](7) NULL,
	[Saturday] [bit] NULL,
	[SaturdayTime] [time](7) NULL,
	[Sunday] [bit] NULL,
	[SundayTime] [time](7) NULL,
	[TypeCostApply] [nchar](1) NULL,
	[WhereDeductCostHair] [nchar](1) NULL,

    CONSTRAINT [FK_COMPANY_REGISTER] FOREIGN KEY([IdMainRegister]) REFERENCES [dbo].[REGISTER] ([IDRegister])
)
