CREATE TABLE [dbo].[JOBCONSUMPTION]
(
	[IDJobConsump] INT NOT NULL PRIMARY KEY IDENTITY,
	[IDJobDone] [int] NOT NULL,
	[IDHair] [int] NOT NULL,
	[IDColor] [int] NOT NULL,
	[QttyPacks] [real] NULL,
	[HairProvided] [bit] NULL,
	CONSTRAINT [FK_JOBCONSUMPTION_HAIR] FOREIGN KEY([IDHair]) REFERENCES [dbo].[HAIR] ([IDHair]),
	CONSTRAINT [FK_JOBCONSUMPTION_COLOR] FOREIGN KEY([IDColor]) REFERENCES [dbo].[COLOR] ([IdColor]),
	CONSTRAINT [FK_JOBCONSUMPTION_JOBDONE] FOREIGN KEY([IDJobDone]) REFERENCES [dbo].[JOBDONE] ([IDJobDone])
)
