CREATE TABLE [dbo].[JOBEXECUTER]
(
	[IDJobExecut] INT NOT NULL PRIMARY KEY IDENTITY,
	[IDJobDone] [int] NOT NULL,
	[IDBraider] [int] NOT NULL,
	[BraidingLocat] [nchar](1) NULL,

	CONSTRAINT [FK_JOBEXECUTER_BRAIDER] FOREIGN KEY([IDBraider]) REFERENCES [dbo].[BRAIDER] ([IDBraider]),
	CONSTRAINT [FK_JOBEXECUTER_JOBDONE] FOREIGN KEY([IDJobDone]) REFERENCES [dbo].[JOBDONE] ([IDJobDone]),
)
