CREATE TABLE [dbo].[SALESDETAILS]
(
	[IDSaleDetail] INT NOT NULL PRIMARY KEY IDENTITY,
	[IDSale] [int] NOT NULL,
	[IDProd] [int] NOT NULL,
	[UnitPrice] [money] NULL,
	[QttySale] [real] NULL,
	CONSTRAINT [FK_SALESDETAILS_PRODUCT] FOREIGN KEY([IDProd]) REFERENCES [dbo].[PRODUCT] ([IDProd]),
	CONSTRAINT [FK_SALESDETAILS_SALES] FOREIGN KEY([IDSale]) REFERENCES [dbo].[SALES] ([IDSale]),
)
