CREATE TABLE [dbo].[SKILLS]
(
	[IDSkill] INT NOT NULL PRIMARY KEY IDENTITY,
	[IDBraider] [int] NOT NULL,
	[IDStyle] [int] NOT NULL,
	CONSTRAINT [FK_SKILLS_BRAIDER] FOREIGN KEY([IDBraider]) REFERENCES [dbo].[BRAIDER] ([IDBraider]),
	CONSTRAINT [FK_SKILLS_STYLE] FOREIGN KEY([IDStyle]) REFERENCES [dbo].[STYLE] ([IDStyle]),
)
