CREATE TABLE [dbo].[USERSROLES]
(
	[IDUserRole] INT NOT NULL IDENTITY PRIMARY KEY,
	[IDUser] [int] NULL,
	[IDRole] [int] NULL,

	CONSTRAINT [FK_USERSROLES_ROLES] FOREIGN KEY (IDRole) REFERENCES ROLES(IDRole), 
	CONSTRAINT [FK_USERSROLES_USERS] FOREIGN KEY (IDUser) REFERENCES USERS(IDUser), 
)
